[package]
name = "webway-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

# Core binary parsing
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
byteorder = "1.5"
bytes = "1.4"

# Advanced parsing
nom = "7.1"
deku = "0.16"

# Protocol support
prost = "0.12"
rmp-serde = "1.1"

# Utilities
hex = "0.4"
crc = "3.0"
thiserror = "1.0"

# Kafka/Redpanda client
rdkafka = { version = "0.36", features = ["cmake-build", "ssl", "sasl"] }

# Async runtime
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"

# Additional async utilities
futures = "0.3"
async-trait = "0.1"

# JSON handling for Kafka messages
serde_json = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }