services:
  webway-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webway-parser
    image: webway-parser:1.0.0
    volumes:
      - ../webway-data-generation/test_data:/app/test_data:ro
      - ./output:/app/output
    environment:
      - RUST_LOG=debug
      - DATA_PATH=/app/test_data/sensor_data.bin
