networks:
  redpanda_network:
    external: true
    name: redpanda-quickstart-one-broker_redpanda_network

services:
  webway-parser:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: webway-parser
    image: webway-parser:1.6.0
    volumes:
      - ./src:/app/src/
    environment:
      - RUST_LOG=debug
      - DATA_PATH=/app/test_data/sensor_data.bin
      - KAFKA_BROKERS=redpanda-0:9092
      - KAFKA_TOPIC=sensor-data
    networks:
      - redpanda_network
    tty: true