networks:
  redpanda_network:
    external: true
    name: redpanda-quickstart-one-broker_redpanda_network

services:
  webway-c:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: webway-c
    image: webway-c:1.0.0
    volumes:
      - ../webway-data-generation/test_data:/app/test_data:ro
      - ./output:/app/output
      - ./src:/usr/src/app/src
    environment:
      - LOG_LEVEL=debug
      - DATA_PATH=/app/test_data/sensor_data.bin
      - KAFKA_BROKERS=redpanda-0:9092
      - KAFKA_TOPIC=sensor-data
      - CC=gcc
      - CXX=g++
    networks:
      - redpanda_network
    command: ["/bin/bash"]
    tty: true