name: Validate Changesets

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  validate-changesets:
    name: Validate Changesets Required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Remove cache: 'yarn' since we're using corepack

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for changesets
        id: changeset-check
        run: |
          # Check if there are any changesets in the PR
          if [ -n "$(ls .changeset/*.md 2>/dev/null | head -1)" ]; then
            # Exclude the README.md and template files
            changeset_files=$(ls .changeset/*.md 2>/dev/null | grep -v README.md | grep -v template.md || true)
            if [ -n "$changeset_files" ]; then
              echo "changesets_found=true" >> $GITHUB_OUTPUT
              echo "✅ Changesets found in PR"
              echo "Changeset files:"
              echo "$changeset_files"
            else
              echo "changesets_found=false" >> $GITHUB_OUTPUT
              echo "❌ No changesets found in PR"
            fi
          else
            echo "changesets_found=false" >> $GITHUB_OUTPUT
            echo "❌ No changesets found in PR"
          fi

      - name: Validate changeset status
        run: yarn changeset:status

      - name: Comment on PR if no changesets
        if: steps.changeset-check.outputs.changesets_found == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ⚠️ Missing Changeset

            This PR doesn't include a changeset. If this PR contains changes that should be released, please add a changeset:

            \`\`\`bash
            yarn changeset
            \`\`\`

            Then follow the prompts to describe your changes.

            ### What is a changeset?
            A changeset is a file that describes the changes you've made and helps us automatically:
            - Generate changelogs
            - Determine version bumps (patch/minor/major)
            - Create releases

            ### When to skip changesets:
            - Documentation-only changes
            - Internal tooling updates
            - Test updates
            - CI/CD changes

            If this PR intentionally doesn't need a changeset, please add the \`skip-changeset\` label.`
            })

      - name: Fail if no changesets and no skip label
        if: steps.changeset-check.outputs.changesets_found == 'false' && !contains(github.event.pull_request.labels.*.name, 'skip-changeset')
        run: |
          echo "❌ This PR requires a changeset or the 'skip-changeset' label"
          echo "Run 'yarn changeset' to create one, or add the 'skip-changeset' label if this PR doesn't need a release"
          exit 1